from app.models.workflow_state import WorkflowState
from app.core.llm import get_llm
from langchain_core.prompts import ChatPromptTemplate

def reviewer_node(state: WorkflowState) -> dict:
    """
    Reviewer Agent: Analyzes execution errors and provides corrected prompts to the Coder.
    """
    llm = get_llm()
    
    prompt = ChatPromptTemplate.from_messages([
        ("system", "You are an Expert Code Reviewer. The Python code generated by the Coder Agent failed during execution in the Docker sandbox. Analyze the error traceback and provide clear, specific instructions to the Coder on how to fix the code. Do not write the code yourself, just provide feedback."),
        ("human", "Generated Code:\n{generated_code}\n\nExecution Error:\n{execution_error}\n\nProvide feedback to fix the code:")
    ])
    
    chain = prompt | llm
    
    generated_code = state.generated_code if hasattr(state, "generated_code") else state.get("generated_code", "")
    execution_error = state.execution_error if hasattr(state, "execution_error") else state.get("execution_error", "")
    
    response = chain.invoke({
        "generated_code": generated_code,
        "execution_error": execution_error
    })
    
    return {"reviewer_feedback": response.content}
